/**
 * Typed discriminated union message protocol for Focus Guard.
 *
 * All `chrome.runtime.sendMessage` calls between UI contexts and the service worker
 * must use these types. Every message carries a `trace_id` (generated by the sender
 * via `crypto.randomUUID()`) to correlate log entries across the message boundary.
 *
 * Binary fields (e.g., WebAuthn attestation, assertion) use `number[]` — NOT `Uint8Array`.
 * Chrome uses JSON-like serialization (not structured clone) for `chrome.runtime.sendMessage`,
 * so `Uint8Array` becomes a plain object `{0:1, 1:2, ...}`. Senders: `Array.from(uint8Array)`.
 * Receivers: `new Uint8Array(array)`.
 */

import type { Settings } from '@/core/storage';

/** The WebAuthn operation being authorised by an assertion. */
export type AssertionOperation = 'unlock' | 'remove_domain' | 'replace_credential';

/**
 * Messages sent from UI contexts (popup, blocked page) to the service worker.
 * Each variant is a discriminated union on `type`.
 */
export type RequestMessage =
  | { type: 'GET_REGISTRATION_CHALLENGE'; trace_id: string }
  | {
      type: 'REGISTER_CREDENTIAL';
      attestation: number[];
      clientDataJSON: number[];
      trace_id: string;
    }
  | {
      type: 'GET_ASSERTION_CHALLENGE';
      operation: AssertionOperation;
      domain?: string;
      trace_id: string;
    }
  | {
      type: 'VERIFY_ASSERTION';
      authenticatorData: number[];
      clientDataJSON: number[];
      signature: number[];
      transport?: string;
      operation: AssertionOperation;
      domain?: string;
      durationMs?: number;
      trace_id: string;
    }
  | { type: 'GET_CREDENTIAL_STATUS'; trace_id: string }
  | { type: 'ADD_DOMAIN'; domain: string; trace_id: string }
  | { type: 'GET_BLOCKLIST'; trace_id: string }
  | { type: 'GET_UNLOCK_SESSION'; domain: string; trace_id: string }
  | { type: 'GET_SETTINGS'; trace_id: string }
  | { type: 'SET_SETTINGS'; settings: Partial<Settings>; trace_id: string };

/**
 * Responses sent from the service worker back to UI contexts.
 * Discriminated on `ok` — callers should narrow before accessing `data` or `error`.
 */
export type ResponseMessage = { ok: true; data: unknown } | { ok: false; error: string };

/**
 * Builds a successful response payload.
 *
 * @param data - The response data to return to the caller.
 * @returns A `ResponseMessage` with `ok: true`.
 */
export function okResponse(data: unknown): ResponseMessage {
  return { ok: true, data };
}

/**
 * Builds an error response payload.
 *
 * @param error - Human-readable error description.
 * @returns A `ResponseMessage` with `ok: false`.
 */
export function errResponse(error: string): ResponseMessage {
  return { ok: false, error };
}
